services:
  # PostgreSQL Database
  - type: pserv
    name: juliaos-database
    env: postgresql
    plan: free
    ipAllowList: []
    maxConnections: 5
    maintenanceWindow: SUN-03-00-UTC

  # Julia Backend Web Service
  - type: web
    name: juliaos-backend
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: julia --project=@. run_server.jl
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 8052
      - key: HOST_URL
        sync: false
      - key: DB_HOST
        fromService:
          name: juliaos-database
          type: pserv
          property: host
      - key: DB_PORT
        fromService:
          name: juliaos-database
          type: pserv
          property: port
      - key: DB_NAME
        fromService:
          name: juliaos-database
          type: pserv
          property: database
      - key: DB_USER
        fromService:
          name: juliaos-database
          type: pserv
          property: user
      - key: DB_PASSWORD
        fromService:
          name: juliaos-database
          type: pserv
          property: password
      - key: GEMINI_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: X_API_KEY
        sync: false
      - key: X_API_KEY_SECRET
        sync: false
      - key: X_ACCESS_TOKEN
        sync: false
      - key: X_ACCESS_TOKEN_SECRET
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /ping
    autoDeploy: true
